### ISSUE TITLE
build error on line 125 in keyword.cpp

### ISSUE THREAD

**Issue by githubgoucho** [klumw/keyword_detection#1]
nice work!
I got it running with an INMP441 micro ...

but I got a build error on line 125 in keyword.cpp
msg->either all initializer clauses should be designated or none of them should be

change line 125 to
.clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(EI_CLASSIFIER_FREQUENCY),

**Comment by klumw** [comment]
The compatibility issue is fixed.
